export const HERO_SECTION = `HERO_SECTION`;
export const ABOUT_US_SECTION = `ABOUT_US_SECTION`;
export const PROJECT_SECTION = `PROJECT_SECTION`;
export const JOIN_US_SECTION = `JOIN_US_SECTION`;
export const TESTIMONIAL_SECTION = `TESTIMONIAL_SECTION`;
export const FOOTER_SECTION = `FOOTER_SECTION`;
